# Ejercicios capítulo 1.

Ejercicios prácticos de programación en Python con soluciones paso a paso, enfocados en problemas económicos utilizando listas, NumPy y Pandas.

1.Declara las siguientes variables (Ana, edad, estatura, es estudiante) y usa type() para imprimir su tipo:

In [ ]:
nombre = "Ana"
edad = 25
estatura = 1.68
es_estudiante = True

print(type(nombre))
print(type(edad))
print(type(estatura))
print(type(es_estudiante))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

2 .Crea dos variables con números enteros y muestra su suma:

In [ ]:
a = 7
b = 3

print("La suma es:", a + b)

La suma es: 10

3.Declara dos números y verifica si el primero es mayor que el segundo:

In [ ]:
x = 10
y = 20

print("¿x es mayor que y?", x > y)

¿x es mayor que y? False

4.Crea una lista con cuatro frutas y muestra la lista usando print().

In [ ]:
frutas = ["manzana, banana, cereza, durazno"]

print(frutas)

['manzana, banana, cereza, durazno']

5.Muestra los tres primeros elementos de esta lista: 10, 20, 30, 40, 50

In [ ]:
numeros = [10, 20, 30, 40, 50]

print(numeros[:3])

[10, 20, 30]

6.Genera una matriz identidad de 4x4 utilizando np.eye().

In [ ]:

import numpy as np
matriz_identidad = np.eye(4)

print("Matriz identidad 4x4:")
print(matriz_identidad)

Matriz identidad 4x4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

7.Usa print(f"...") para mostrar el nombre y la edad de una persona.

In [ ]:
nombre = "Ana"
edad = 25

print(f"Mi nombre es {nombre} y tengo {edad} años.")

Mi nombre es Ana y tengo 25 años.

8.Crea una tupla con dos valores de coordenadas (latitud, longitud) y accede a cada elemento.

In [ ]:
coordenadas = (19.4326, -99.1332)

print("Latitud:", coordenadas[0])
print("Longitud:", coordenadas[1])

Latitud: 19.4326
Longitud: -99.1332

9.Guarda el nombre, edad y ciudad en un diccionario y muestra el valor asociado a “ciudad”.

In [1]:
persona = {"nombre": "Ana", "edad": 25, "ciudad": "Monterrey"}

print("Ciudad:", persona["ciudad"])

Ciudad: Monterrey

10.Crea un array con los números del 1 al 5 y muéstralo.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]

11.Usa indexación para mostrar el tercer valor del array anterior.

In [ ]:
print(a[2])

3

12.Usa np.array para crear esta matriz y accede al valor en la fila 1, columna 2

In [ ]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])

print(matriz[1, 2])

6

13.Muestra solo la primera fila de la matriz anterior.

In [ ]:
print(matriz[0])

[1 2 3]